-- ============================================================
-- OncoSearch HIU Database
-- ============================================================
-- This is the HIU's (Health Information User) own database.
-- It is SEPARATE from abdm-postgres (the HIP's hospital DB).
-- The HIU is a distinct organization with its own data boundary.
-- ============================================================

-- Tracks the lifecycle of every consent request the HIU initiates.
-- Survives HIU restarts — the source of truth for all transactions.
CREATE TABLE consent_transactions (
    id               SERIAL PRIMARY KEY,
    transaction_id   VARCHAR(100) UNIQUE NOT NULL,   -- "txn-<uuid>" from gateway
    consent_id       VARCHAR(100),                   -- "consent-<uuid>" from gateway
    request_id       VARCHAR(100) NOT NULL,           -- UUID generated by HIU
    abha_address     VARCHAR(100) NOT NULL,           -- e.g. "arjun.mehta@abdm"
    status           VARCHAR(30)  NOT NULL DEFAULT 'AWAITING_DATA',
    -- status values: AWAITING_DATA | DATA_RECEIVED | EXPIRED | ERROR
    purpose_code     VARCHAR(30)  NOT NULL DEFAULT 'CAREMGT',
    data_erase_at    TIMESTAMPTZ  NOT NULL,           -- mirrors consent permission.dataEraseAt
    initiated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    data_received_at TIMESTAMPTZ                     -- set when FHIR webhook fires
);

CREATE INDEX ON consent_transactions(abha_address);
CREATE INDEX ON consent_transactions(data_erase_at);


-- Cached FHIR R4 bundles received from the HIP.
-- Enables data retrieval without re-triggering consent.
-- Enforces retention at query time (expires_at > NOW()) AND by scheduler (is_deleted).
CREATE TABLE health_data_cache (
    id             SERIAL PRIMARY KEY,
    transaction_id VARCHAR(100) NOT NULL REFERENCES consent_transactions(transaction_id) ON DELETE CASCADE,
    abha_address   VARCHAR(100) NOT NULL,           -- denormalized for fast patient lookups
    fhir_bundle    JSONB        NOT NULL,           -- full FHIR R4 Bundle stored as JSONB
    entry_count    INTEGER,                         -- cached from bundle for quick display
    expires_at     TIMESTAMPTZ  NOT NULL,           -- mirrors dataEraseAt; used for filtering + cleanup
    stored_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    is_deleted     BOOLEAN      NOT NULL DEFAULT FALSE,  -- soft-delete flag
    deleted_at     TIMESTAMPTZ                          -- when soft-delete occurred
);

-- Composite index for the retrieval endpoint pattern: patient + not deleted + not expired
CREATE INDEX ON health_data_cache(abha_address, is_deleted, expires_at);
-- Partial index for cleanup job efficiency
CREATE INDEX ON health_data_cache(expires_at) WHERE is_deleted = FALSE;


-- Append-only audit trail.
-- Provides ABDM-required evidence that data was accessed and erased per consent terms.
-- Never updated after insertion.
CREATE TABLE data_access_log (
    id             BIGSERIAL PRIMARY KEY,
    abha_address   VARCHAR(100) NOT NULL,
    transaction_id VARCHAR(100),          -- NULL for system-level actions
    action         VARCHAR(50)  NOT NULL,
    -- action values: CONSENT_TRIGGERED | DATA_RECEIVED | DATA_ACCESSED | DATA_EXPIRED | DATA_DELETED
    accessed_by    VARCHAR(100) NOT NULL DEFAULT 'oncosearch-system',
    occurred_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX ON data_access_log(abha_address, occurred_at DESC);
